# Site
title: Beetle
bio: "Hello, I am Beetle, I am a 3D artist, I am currently creating cosmetic modifications for FF14, and I also make commissions for the order"
description: "Moonrise is a fresh take on the classic Moon"
reading_time: true
words_per_minute: 200
logo: "assets/img/logo.png"
background: "assets/img/moonrise-background.jpg"
tiled_bg: false # Set this true if you want to tile your background image, otherwise it will be covered
locale: en_US
url: https://beetle-purple.github.io/Beetle

# Jekyll
permalink: /:title/
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed

# Comments

# Social
# if you don't have any of social below, comment the line.
#google:
# plus: username
#analytics:
#verify:
#ad-client:
#ad-slot:
#bing-verify:
#email:
twitter: purple_ametist
#facebook: username
#github-url: username
#stackoverflow: 123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin: username
#xing: username
#instagram: username
#lastfm: username
#tumblr: username
#medium: '@username'
#pinterest: username
#foursquare: username
#steam: username
#dribbble: username
#youtube: username
#youtube-channel: channel
#soundcloud: username
#weibo: username
#flickr: username
#codepen: username
#keybase: username
#xmpp: username@server.com
#hackernews: username

# Plugins
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache

jekyll-mentions:
  base_url: https://github.com

# Exclude list
exclude:
  [
    README.md,
    Gemfile,
    Gemfile.lock,
    node_modules,
    gulpfile.js,
    package.json,
    _site,
    src,
    vendor,
    CNAME,
    LICENSE,
    Rakefile,
  ]
